Update build-ffmpeg.yml

diff --git a/.github/workflows/build-ffmpeg.yml b/.github/workflows/build-ffmpeg.yml
--- a/.github/workflows/build-ffmpeg.yml
+++ b/.github/workflows/build-ffmpeg.yml
@@ -43,9 +43,16 @@ jobs:
       - name: Get ffmpeg-stable-autobuild latest build
         id: ffmpeg-stable-autobuild-info
         run: |
-          tag_name=$(gh api repos/$GITHUB_REPOSITORY/releases/latest -q .tag_name)
-          echo git-sha=${tag_name:17:7} >> $GITHUB_OUTPUT
-          echo helper-git-sha=${tag_name:25:7} >> $GITHUB_OUTPUT
+          tag_name=$(gh api repos/$GITHUB_REPOSITORY/releases/latest -q .tag_name || echo "fallback-tag")
+    
+          if [[ "$tag_name" == "fallback-tag" ]]; then
+            echo "Failed to fetch latest release tag, using fallback values"
+            echo git-sha=unknown >> $GITHUB_OUTPUT
+            echo helper-git-sha=unknown >> $GITHUB_OUTPUT
+           else
+            echo git-sha=${tag_name:17:7} >> $GITHUB_OUTPUT
+            echo helper-git-sha=${tag_name:25:7} >> $GITHUB_OUTPUT
+           fi
         env:
           GH_TOKEN: ${{ secrets.TOKEN_REPO }}
 
